In [2]:
import numpy as np

In [3]:
vector = np.arange(10, 50)
print("Vector:", vector)

Vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:", matrix_3x3)

3x3 Matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:", identity_matrix)

3x3 Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
array_3x3x3 = np.random.rand(3, 3, 3)
print("3x3x3 Random Array:", array_3x3x3)

3x3x3 Random Array: [[[0.70332193 0.40228271 0.68172194]
  [0.23591123 0.21137572 0.53085145]
  [0.24552268 0.00550358 0.16560957]]

 [[0.54688431 0.7756625  0.79452005]
  [0.10121794 0.31532093 0.52029959]
  [0.86992373 0.92652147 0.16946812]]

 [[0.73099173 0.19486785 0.1754702 ]
  [0.25254035 0.54482939 0.97226884]
  [0.12597077 0.55932452 0.33663701]]]


In [8]:
array_10x10 = np.random.rand(10, 10)
print("Min Value:", np.min(array_10x10), "Max Value:", np.max(array_10x10))

Min Value: 0.010500069174420812 Max Value: 0.9875258879399892


In [9]:
random_vector = np.random.rand(30)
print("Mean Value:", np.mean(random_vector))


Mean Value: 0.47800953073491254


In [10]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print("Normalized 5x5 Matrix:", normalized_matrix)

Normalized 5x5 Matrix: [[0.55447528 0.55369862 0.83160361 0.76509021 0.02986799]
 [0.00824014 0.9209852  0.28497884 0.33194878 0.77715948]
 [0.28113569 0.2524034  0.04759798 0.         0.98712219]
 [0.33271107 0.28030097 0.5803054  0.89641883 0.5793984 ]
 [0.38270047 0.25987061 0.42569719 0.70222153 1.        ]]


In [11]:
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)
matrix_product = np.dot(matrix_5x3, matrix_3x2)
print("Matrix Product (5x3 * 3x2):", matrix_product)

Matrix Product (5x3 * 3x2): [[0.59983372 0.40008332]
 [0.31319187 0.22393711]
 [0.18687506 0.28387166]
 [0.50979887 0.32316104]
 [0.56401488 0.46276532]]


In [12]:
matrix_A = np.random.rand(3, 3)
matrix_B = np.random.rand(3, 3)
dot_product = np.dot(matrix_A, matrix_B)
print("Dot Product of Two 3x3 Matrices:", dot_product)

Dot Product of Two 3x3 Matrices: [[0.40416623 0.33617835 0.88561045]
 [0.90280627 0.98787126 1.17346469]
 [0.49635285 0.48235869 0.82497257]]


In [13]:
matrix_4x4 = np.random.rand(4, 4)
transpose_matrix = matrix_4x4.T
print("Transpose of 4x4 Matrix:", transpose_matrix)

Transpose of 4x4 Matrix: [[5.77107436e-04 1.65490344e-01 3.61091879e-01 5.14358817e-01]
 [3.47653290e-01 9.34865410e-01 9.41828202e-01 6.08041372e-01]
 [3.52392029e-01 7.46762579e-01 4.04141895e-01 8.69685856e-01]
 [6.38445742e-02 2.01401448e-01 5.04007963e-01 6.90015278e-01]]


In [14]:
det_matrix = np.random.rand(3, 3)
determinant = np.linalg.det(det_matrix)
print("Determinant of 3x3 Matrix:", determinant)

Determinant of 3x3 Matrix: 0.18323767384578918


In [15]:
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)
matrix_product_AB = np.dot(A, B)
print("Matrix Product A (3x4) * B (4x3):", matrix_product_AB)

Matrix Product A (3x4) * B (4x3): [[0.85416493 0.88608497 0.57382816]
 [0.81440763 0.76014061 0.4755887 ]
 [1.17245876 1.09469402 1.2087661 ]]


In [16]:
matrix_3x3 = np.random.rand(3, 3)
vector_3x1 = np.random.rand(3, 1)
matrix_vector_product = np.dot(matrix_3x3, vector_3x1)
print("Matrix-Vector Product:", matrix_vector_product)


Matrix-Vector Product: [[1.09610352]
 [0.9234953 ]
 [0.85311906]]


In [17]:
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
x = np.linalg.solve(A, b)
print("Solution to Ax = b:", x)

Solution to Ax = b: [[ 0.71493699]
 [-0.17666806]
 [-0.37664714]]


In [18]:
matrix_5x5 = np.random.rand(5, 5)
row_sums = np.sum(matrix_5x5, axis=1)
column_sums = np.sum(matrix_5x5, axis=0)
print("Row-wise Sums:", row_sums)
print("Column-wise Sums:", column_sums)

Row-wise Sums: [3.02686573 3.3210681  3.80939411 1.41415341 2.68305569]
Column-wise Sums: [3.06765808 2.41636783 2.10514827 3.22927006 3.43609279]
